version: 2.1
jobs:
  build:
   docker:
     - image: cimg/node:lts

   working_directory: /tmp
   steps:

      - run:
          name: ダミー アーティファクトの作成
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - run:
          name: jFrog CLI のインストール
          command: curl -fL https://getcli.jfrog.io | sh

      - run:
          name: Artifactory へのプッシュ
          command: |
            ./jfrog config add --artifactory-url https://taca17.jfrog.io/artifactory/ --user rockhop17g@gmail.com --apikey AKCp8ihLMCzJ3XhHSdPeFR7bRVA7YxKG6aQHCAp8bCJ4RP6HcPifzd7ro5CfUSnrV6KpJS2xR --interactive=false
            ./jfrog rt u "/tmp/artifact-1" libs-released-local
       - run:
          name: フォルダ確認
          command: |
            pwd;
