version: 2.1
jobs:
  build:
   docker:
     - image: cimg/node:lts

   working_directory: /tmp
   steps:

      - run:
          name: ダミー アーティファクトの作成
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - run:
          name: jFrog CLI のインストール
          command: curl -fL https://getcli.jfrog.io | sh

      - run:
          name: Artifactory へのプッシュ
          command: |
            ./jfrog rt config --url https://takapractice.jfrog.io/artifactory/libs-release-local/ --user rock_hop_17@yahoo.co.jp --apikey AP78fs2Zvx7YXUfAZnZAcg3Qcj5 --interactive=false
            ./jfrog rt u "/tmp/*.*" "libs-release-local/"
